### ISSUE TITLE
Keep master branch clean from reports.

### ISSUE THREAD

**Issue by georgeyord** [kostis-codefresh/codefresh-plugin-checker#1]
To keep your master branch clean from the auto-generated commits of the reports, I would suggest to link [https://kostis-codefresh.github.io/codefresh-plugin-checker/](https://kostis-codefresh.github.io/codefresh-plugin-checker/) to a different branch than `master`. This way your application logic will be easily demonstrated by following the commits on `master` branch while the report generation will continue on the new branch. I would suggest to use `gh-pages` as the name of the new branch which is a common practise.

To achieve this, you need to amend `codefresh.yml` to accomodate the new flow. In detail, you need to use the new branch during the `analyze` phase and don't forget to rebase/merge the changes from `master` branch before pushing.

**Comment by kostis-codefresh** [comment]
Fixed by https://github.com/kostis-codefresh/codefresh-plugin-checker/commit/59924483a57d6f69f79d1daec1d8bdb3c1c27cd4 and https://github.com/kostis-codefresh/codefresh-plugin-checker/commit/7f3249a54125532cca575f8d6393ad42fccc9635

gh-pages doesn't work like master. While master can work with /docs folder, gh-pages does not. It needs to contain all HTML at the root folder of the branch
